services:
  web:
    build: ./web
    container_name: web
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
    depends_on:
      - api

  api:
    build: ./API/
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./API/:/app/
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
